// automatically generated by the FlatBuffers compiler, do not modify

package pkg.flatbuffers.rmod;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Record extends Table {
    public static Record getRootAsRecord(ByteBuffer _bb) {
        return getRootAsRecord(_bb, new Record());
    }

    public static Record getRootAsRecord(ByteBuffer _bb, Record obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static int createRecord(FlatBufferBuilder builder,
                                   int targetOffset,
                                   int uriOffset,
                                   long ts,
                                   int requestOffset,
                                   int responseOffset) {
        builder.startObject(5);
        Record.addTs(builder, ts);
        Record.addResponse(builder, responseOffset);
        Record.addRequest(builder, requestOffset);
        Record.addUri(builder, uriOffset);
        Record.addTarget(builder, targetOffset);
        return Record.endRecord(builder);
    }

    public static void startRecord(FlatBufferBuilder builder) {
        builder.startObject(5);
    }

    public static void addTarget(FlatBufferBuilder builder, int targetOffset) {
        builder.addOffset(0, targetOffset, 0);
    }

    public static void addUri(FlatBufferBuilder builder, int uriOffset) {
        builder.addOffset(1, uriOffset, 0);
    }

    public static void addTs(FlatBufferBuilder builder, long ts) {
        builder.addLong(2, ts, 0L);
    }

    public static void addRequest(FlatBufferBuilder builder, int requestOffset) {
        builder.addOffset(3, requestOffset, 0);
    }

    public static void addResponse(FlatBufferBuilder builder, int responseOffset) {
        builder.addOffset(4, responseOffset, 0);
    }

    public static int endRecord(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public Record __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public String target() {
        int o = __offset(4);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer targetAsByteBuffer() {
        return __vector_as_bytebuffer(4, 1);
    }

    public ByteBuffer targetInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 4, 1);
    }

    public String uri() {
        int o = __offset(6);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer uriAsByteBuffer() {
        return __vector_as_bytebuffer(6, 1);
    }

    public ByteBuffer uriInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 6, 1);
    }

    public long ts() {
        int o = __offset(8);
        return o != 0 ? bb.getLong(o + bb_pos) : 0L;
    }

    public String request() {
        int o = __offset(10);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer requestAsByteBuffer() {
        return __vector_as_bytebuffer(10, 1);
    }

    public ByteBuffer requestInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 10, 1);
    }

    public String response() {
        int o = __offset(12);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer responseAsByteBuffer() {
        return __vector_as_bytebuffer(12, 1);
    }

    public ByteBuffer responseInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 12, 1);
    }
}

